title: android mdm agent
baseurl: "/android-mdm-agent"
url: "http://flyve.org"
image: http://flyve.org/android-mdm-agent/images/logo2.png
email: ml-flyvemdm@teclib.com
twitter: https://twitter.com/flyvemdm
facebook: https://www.facebook.com/FlyveMDM
googlePlus: https://plus.google.com/collection/c32TsB
telegram: https://t.me/flyvemdm
irc: http://webchat.freenode.net/?channels=flyve-mdm
reddit: https://www.reddit.com/r/FlyveMDM/

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap

repository: flyve-mdm/android-mdm-agent

prose:

  rooturl: '_posts' 
  
  ignore:
    - .keep

  media: "images"

  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "hackerNewsURL"
        field:
          element: "text"
          label: Hacker News URL
          value: ""
      - name: "redditURL"
        field:
          element: "text" 
          label: Reddit URL
          value: ""

    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "howtos"
        field:
          element: "checkbox"
          label: "howtos"
          value: false
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
      - name: "hackerNewsURL"
        field:
          element: "text"
          label: Hacker News URL
          value: ""
      - name: "redditURL"
        field:
          element: "text" 
          label: Reddit URL
          value: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
