title: android agent
email: ml-flyvemdm@teclib.com
twitter: flyvemdm
baseurl: "/flyve-mdm-android-agent"
url: "http://flyve.org"   
image: http://flyve.org/flyve-mdm-android-agent/images/logo2.png
  

# Build settings
markdown: kramdown

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap

repository: flyve-mdm/flyve-mdm-android-agent

defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

collections:
  coverage:
    output: true

prose:

  rooturl: '_posts' 
  
  ignore:
    - .keep

  media: "images"

  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "hackerNewsURL"
        field:
          element: "text"
          label: Hacker News URL
          value: ""
      - name: "redditURL"
        field:
          element: "text" 
          label: Reddit URL
          value: ""

    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "wiki"
        field:
          element: "checkbox"
          label: "wiki"
          value: false
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
      - name: "hackerNewsURL"
        field:
          element: "text"
          label: Hacker News URL
          value: ""
      - name: "redditURL"
        field:
          element: "text" 
          label: Reddit URL
          value: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
