version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-stretch-node
    working_directory: ~/project-site
    branches:
      only:
        - gh-pages
        - /feature/.*/
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-cache-{{ checksum "package-lock.json" }}
      - run:
           name: "Install environment"
           command:  source ci/installation.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: "Run tests"
          command: npm test
      - run:
          name: "Run Muffet"
          command: |
            EXC=".*\.com|bugsnag|t\.me|\.io|malware|deeplink|blackberry-|ios-|glpi|docker-|windows-|legacy-|backend-|demo-|graphql-|-dashboard"
            muffet -c 100 -e $EXC -f http://flyve.org/android-mdm-agent/